# Generated by Django 4.2.11 on 2024-04-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
